# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "April Elizabeth"
description: > 
   Sometimes writer, always hungry.

#blog logo
logo: "/assets/images/hikegirl.jpg"
float_logo: true # true, false (default)

cover: "/assets/images/chief_header.jpg"

name: 'April'
author: 'April'
author_image: "/assets/images/hikegirl.jpg"

paginate:	7

url: "https://aprilelizabeth.net"
baseurl: ""

google_analytics:

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/AprilElizabeth
    desc:	Peek under the hood
  - icon:   keybase
    url:    https://keybase.io/spinachbaby
    desc:   Chat me on Keybase
