# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "April Elizabeth"
description: > 
   Sometimes writer, always hungry.

#blog logo
logo: "/assets/images/hikegirl.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/chief_header.jpg"

name: 'April'
author: 'April'
author_image: "/assets/images/yrstruly.jpg"

paginate:	5

url: "https://aprilelizabeth.net" # the base hostname & protocol for your site
baseurl: ""

#disqus: disqus-shortname
google_analytics: UA-142144768-1

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/AprilElizabeth
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
