title: turtlemadness
description: >- 
  My partner asked me what I wanted this website to be.
  I told him, sometimes I just like to write things.

baseurl: "" 
url: "https://turtlemadness.net" 
github_username:  AprilElizabeth

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Github pages settings
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
